name: Deploy production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: hotel-price-api-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on:
      - self-hosted
      - linux
      - x64
      - hotel-api

    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /home/ubuntu/hotel-api
          bash deploy.sh
